id: I7347144A
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:31:28.757152
last_modified: 2023-01-04 11:31:28.757164
source_metadata:
  collections:
  - Chögyal Pakpa Lodrö Gyaltsen
  - Works of Tibetan Masters
bases:
  D550:
    title: Thirty-Seven Point Maṇḍala Offering
    base_file: D550.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
